# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: ML project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Currently directory
      run: |
         pwd
         ls -la
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine truffleHog
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    #- name: Super-Linter
    #  uses: github/super-linter@v3.15.3    
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: python
    - name: Secret Scan
      run: |
        which trufflehog 
        #trufflehog –regex --json file:///home/runner/work/publicsecurerepo/publicsecurerepo
        trufflehog --entropy true file:"//$PWD"
        
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1  
    - name: Docker linter - Hadolint
      run: docker run --rm -i hadolint/hadolint < Dockerfile     
    #- name: Scan image
    #  uses: anchore/scan-action@v2
    #  with:
    #    image: "localbuild/testimage:latest"
    - name: owasp ZAP baseline scan
      run: docker run -t owasp/zap2docker-stable zap-full-scan.py -d -a -r report_html -t <https://www.example.com> -P 443
      
      
  
