# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: ML project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Super-Linter
      uses: github/super-linter@v3.15.3    
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: python
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1  
    - name: Docker linter   
      uses: brpaz/hadolint-action@v1.2.1
      with:
        dockerfile: Dockerfile 
    - name: Docker linter - Hadolint     
      uses: addnab/docker-run-action@v2
      with:
        registry: ghcr.io/hadolint
        image: hadolint:latest
        run: |
          echo "Running Script"
          /work/run-script     
        

